# Generated by Django 3.2 on 2021-04-23 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AccountApp', '0002_sellerinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SellerInfo',
        ),
    ]
